import LoginPage from '@/components/Login/Login';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'UMS | Login',
  description: 'Generated by create next app',
}

const Login = () => {
  return (
    <>
      <LoginPage></LoginPage>
    </>
  )
}

export default Login